[project]
site_name = "asimpy"
docs_dir = "pages"
site_dir = "docs"

nav = [
  { "Home" = "index.md" },
  { "Project" = [
    { "License" = "license.md" },
    { "Code of Conduct" = "conduct.md" },
    { "Design" = "design.md" },
  ]},
  { "API" = [
    { "Core" = "api/core.md" },
    { "Queue" = "api/queue.md" },
    { "Resource" = "api/resource.md" },
    { "Store" = "api/store.md" },
    { "Container" = "api/container.md" },
    { "Barrier" = "api/barrier.md" },
    { "All Of" = "api/allof.md" },
    { "First Of" = "api/firstof.md" },
    { "Preemptive" = "api/preemptive.md" },
  ]},
  { "Tutorial" = [
    { "Sleep Once" = "tutorial/01_sleep_once.md" },
    { "Producer-Consumer" = "tutorial/02_producer_consumer.md" },
    { "Bounded Queue" = "tutorial/03_bounded_queue.md" },
    { "Barrier" = "tutorial/04_barrier.md" },
    { "Resource" = "tutorial/05_resource.md" },
    { "Container" = "tutorial/06_container.md" },
    { "Priority Queue" = "tutorial/07_priority_queue.md" },
    { "Store" = "tutorial/08_store.md" },
    { "AllOf" = "tutorial/09_all_of.md" },
    { "FirstOf" = "tutorial/10_first_of.md" },
    { "Interrupt" = "tutorial/11_interrupt.md" },
    { "Preemptive Resource" = "tutorial/12_preemptive.md" },
  ]},
]

[project.markdown_extensions.fenced_code]                                                                        

[project.markdown_extensions.pymdownx.snippets]
base_path = ["."]

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = false
